- docs/v1.0/en/tools/slopes/README.md
- docs/v1.0/en/tools/slopes/send-coins.md
Similar to my [Slopes PR](https://github.com/ava-labs/slopes/pull/17)
* Add `await` keyword for async `makeUnsignedTx` call
* Replace nonexistent `amount` args with `sendAmount` vars
* Replace `makeUnsignedTx`'s 4th and 5th args with array of strings instead of array of buffers
> More updates to README

- docs/v1.0/en/tools/slopes/api/classes/_index_.slopes.md
- docs/v1.0/en/tools/slopes/api/classes/_slopes_.slopescore.md
Similar to the [Slopes PR](https://github.com/ava-labs/slopes/pull/18).
Noticed a small typo in 4 places. This fixes it. 🎩
> Update reolve to resolve.

- docs/v1.0/en/quickstart/ava-getting-started.md
> fix: typos in quickstart.md

- docs/v1.0/en/tutorials/adding-validators.md
* Fix broken link from adding validators tutorial to atomic swap tutorial.
> Fix broken link

- docs/v1.0/en/api/platform.md
- docs/v1.0/en/quickstart/ava-getting-started.md
Fix `platform.addDefaultSubnetValidator` calls in platform docs and getting started tutorial.
> Fix `platform.addDefaultSubnetValidator` calls

- docs/v1.0/en/api/avm.md
- docs/v1.0/en/tools/slopes/README.md
- docs/v1.0/en/tools/slopes/api/classes/_apis_avm_api_.avmapi.md
- docs/v1.0/en/tools/slopes/create-asset.md
- docs/v1.0/en/tools/slopes/managing-keys.md
- docs/v1.0/en/tools/slopes/send-coins.md
* Update default network refs in docs
* Update `makeUnsignedTx ` to `makeBaseTx` in slopes docs
* Update return values from `TxUnsigned ` to `UnsignedTx`
* Update X-Address and assetID 
* Update return `balance` type
* Add returned `utxoIDs` array 
* Add return obj with `txID` and `outputIndex` properties
> Docs update for Slopes and avm.getBalance

- docs/v1.0/en/tools/slopes/create-asset.md
* Replace SecpOutBase with new SecpOutput syntax.
> Update syntax in Slopes "Create Asset" docs

- docs/v1.0/en/api/platform.md
Add `address` to returned values of :
* `platform.getCurrentValidators` 
* `platform.getPendingValidators`
> Update Platform docs

- docs/v1.0/en/api/avm.md
- docs/v1.0/en/api/platform.md
* Add docs for `avm.getTx`
* use `"id": 1` for all curl request/response examples.
> Update `avm` docs

- docs/v1.0/en/references/avm-transaction-serialization.md
Previously `00 00 00 0f` and now `00 00 00 0e`
> Update NFT Credential ID in tx serialization doc.

- docs/v1.0/en/api/issuing-api-calls.md
- docs/v1.0/en/references/glossary.md
> references: Define CB58 in the glossary

- mkdocs.yml
* Add Info docs to nav bar
* Alphabetize APIs
> Add Info API docs to nav bar and alphabetize APIs

- docs/v1.0/en/api/info.md
* info.getNetworkName
* info.getNodeVersion
* Alphabetize RPC calls
> Update Info RPC docs

- docs/v1.0/en/api/admin.md
* Remove the following endpoints as they are now duplicated in `info`
* `admin.peers`
* `admin.getNodeID`
* `admin.getBlockchainID`
* `admin.getNodeVersion`
* `admin.getNetworkName`
* Alphabetize remaining `admin` endpoints
> Update admin RPC docs

- docs/v1.0/en/api/keystore.md
* Alphabetize the `keystore` RPC docs.
> Update keystore RPC docs

- docs/v1.0/en/api/metrics.md
- docs/v1.0/en/api/platform.md
* Alphabetize `platform` RPC docs
> Update platform RPC docs

- docs/v1.0/en/faq/faq.md
- docs/v1.0/en/tutorials/adding-validators.md
- docs/v1.0/en/tutorials/create-a-subnet.md
- docs/v1.0/en/tutorials/creating-a-local-testnet.md
* Update `admin.*` examples to `info.*` where needed
* Add "P Chain" to steps to make it clearer who the `signer` is
> Docs updates

- docs/v1.0/en/faq/faq.md
* Faq for the recent HD web wallet update
> Add web wallet faq.

- docs/v1.0/en/faq/faq.md
Didn't realize known issues were supposed to be at the bottom.
> Moving questions above "Common Problems" and "Known Issues" sections.

- docs/v1.0/en/api/avm.md
- docs/v1.0/en/tutorials/adding-validators.md
- docs/v1.0/en/tutorials/atomic-swap.md
- docs/v1.0/en/tutorials/create-a-blockchain.md
- docs/v1.0/en/tutorials/create-a-subnet.md
- docs/v1.0/en/tutorials/fixed-cap-asset.md
- docs/v1.0/en/tutorials/variable-cap-asset.md
* Fix typo
* Use `"id": 1` for all curl examples
> Fix typo and examples

- docs/v1.0/en/references/platform-transaction-serialization.md
* `AddDefaultSubnetDelegatorTx` specification.
> Platform VM spec update

- docs/v1.0/en/papers/index.md
> ava->avalanche

- docs/v1.0/en/api/info.md
- docs/v1.0/en/api/platform.md
* `platform.createAddress`
* `platform.getBalance`
* `platform.listAddresses`
* `platform.getHeight`
* `platform.getUTXOs`
* `platform.addDefaultSubnetDelegator`
* `platform.createAccount`
* `platform.listAccounts`
* `platform.getAccount`
* `platform.importAVA`
* `platform.exportKey`
* `platform.getPendingValidators`
* `platform.addDefaultSubnetValidator`
* `platform.addNonDefaultSubnetValidator`
* `info.getNodeID`
> Platform utxo-ification docs

- docs/v1.0/en/references/platform-transaction-serialization.md
- mkdocs.yml
* `BaseTx`
* `AddDefaultSubnetDelegatorTx`
> Platform Transaction Serialization doc

- docs/v1.0/en/tools/avalanche.js/create-asset.md
- docs/v1.0/en/tools/avalanche.js/managing-keys.md
- docs/v1.0/en/tools/avalanche.js/send-coins.md
> updated avalanche.js docs a bit

- docs/v1.0/en/tools/avalanche.js/api/README.md
- docs/v1.0/en/tools/avalanche.js/api/classes/common_constants.defaults.md
- docs/v1.0/en/tools/avalanche.js/api/globals.md
- docs/v1.0/en/tools/avalanche.js/api/modules/common_constants.md
- docs/v1.0/en/tools/avalanche.js/api/modules/src_utils.md
* avalanche.js v2.4.2 docs update
> Avalanche.js updates

- docs/v1.0/en/core-concepts/overview.md
Made few rewordings to the docs to enable easier readability
> Made few rewordings to the docs

- docs/v1.0/en/references/avm-transaction-serialization.md
* Add `destination_chain` and `DestinationChain` to the AVM `ExportTx` specification
* Format `type_id` and `Type ID`
> Add DestinationChain to AVM ExportTx

- docs/v1.0/en/api/avm.md
Waiting on https://github.com/ava-labs/gecko/pull/330 to merge
> add memo to send API

- docs/v1.0/en/references/avm-transaction-serialization.md
Add `ImportTx` and `ExportTx` to Unsigned Tx description
> Update AVM Tx Specification

- docs/v1.0/en/references/platform-transaction-serialization.md
* Move `Weight` property behind start_time and end_time.
> Update PlatformVM AddValidator spec example

- docs/v1.0/en/api/evm.md
> Add AVAX specific C Chain RPC calls

- docs/v1.0/en/api/evm.md
> Update C Chain API Docs

- docs/v1.0/en/api/evm.md
Add `exportAVAX` and `importAVAX` RPC Calls
> Update C Chain RPC docs

- docs/v1.0/en/references/platform-transaction-serialization.md
* `CreateSubnetTx` spec for the Platform VM
> PlatformVm CreateSubnetTx spec.

- docs/v1.0/en/api/ipc.md
This reflects the changes from [Gecko PR 360](https://github.com/ava-labs/gecko/pull/360).
> TWEAK: Update IPC docs to reflect latest changes.

- docs/v1.0/en/api/auth.md
Update `--api-require-auth` to `--api-auth-required`
> Update auth flags

- docs/v1.0/en/references/platform-transaction-serialization.md
* `StakeableLockIns`
* `StakeableLockOuts`
> Update PlatformVM Spec

- docs/v1.0/en/api/avm.md
- docs/v1.0/en/api/health.md
- docs/v1.0/en/api/platform.md
- docs/v1.0/en/api/timestamp.md
* Update health response.
* formatting
> General docs updates

- docs/v1.0/en/api/platform.md
* add new min fees 
* add max stake value
> Update docs on delegation and validation 

- docs/v1.0/en/faq.md
- docs/v1.0/en/references/command-line-interface.md
- docs/v1.0/en/references/glossary.md
* Update command line args.
* Update FAQ
* Update glossary
> Update docs w/ Fuji references

- docs/v1.0/en/references/command-line-interface.md
The external port was removed from the code.
> remove http port external param

- docs/v1.0/en/references/platform-transaction-serialization.md
Fix formatting for platform serialization
Clarify meaning of `Stake` field in AddDelegatorTx and AddValidatorTx
> Update docs for staking outputs

- docs/v1.0/en/api/avm.md
Update `avm.sendMultiple` and `wallet.sendMultiple` examples to show sending multiple assets.
> Update `avm.sendMultiple` and `wallet.sendMultiple` examples

- docs/v1.0/en/faq.md
If you have IPv6, you can force IPv4..
> Dig command ipv4
